// Generated by CoffeeScript 1.6.3
(function() {
  var Resource, app, auth, express, io, server;

  express = require('express');

  Resource = require('express-resource');

  app = express();

  auth = require('./resource/auth');

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  app.set('port', process.env.PORT || 8000);

  app.use(express.bodyParser());

  app.use(express["static"]('public'));

  app.use(express.errorHandler());

  app.resource('api/users', require('./resource/users'));

  app.resource('api/items', require('./resource/items'));

  app.resource('api/suppliers', require('./resource/suppliers'));

  app.resource('api/customers', require('./resource/customers'));

  app.post('/auth/login', function(req, res) {
    return auth.credentials(req, res);
  });

  server.listen(app.get('port'), function() {
    return console.log('Running on http://localhost:8000');
  });

  io.sockets.on('connection', function(socket) {
    socket.on('create:item', function(data) {
      return io.sockets.emit('create:item', data);
    });
    socket.on('update:item', function(data) {
      return io.sockets.emit('update:item', data);
    });
    socket.on('delete:item', function(data) {
      return io.sockets.emit('delete:item', data);
    });
    socket.on('search:item', function(data) {
      return socket.emit('search:item', data);
    });
    socket.on('create:supplier', function(data) {
      return io.sockets.emit('create:supplier', data);
    });
    socket.on('update:supplier', function(data) {
      return io.sockets.emit('update:supplier', data);
    });
    socket.on('delete:supplier', function(data) {
      return io.sockets.emit('delete:supplier', data);
    });
    socket.on('search:supplier', function(data) {
      return socket.emit('search:supplier', data);
    });
    socket.on('create:customer', function(data) {
      return io.sockets.emit('create:customer', data);
    });
    socket.on('update:customer', function(data) {
      return io.sockets.emit('update:customer', data);
    });
    socket.on('delete:customer', function(data) {
      return io.sockets.emit('delete:customer', data);
    });
    return socket.on('search:customer', function(data) {
      return socket.emit('search:customer', data);
    });
  });

}).call(this);
