// Generated by CoffeeScript 1.6.3
(function() {
  var resources;

  resources = [
    {
      users: db.UserModel
    }, {
      items: db.ItemModel
    }, {
      suppliers: db.SupplierModel
    }, {
      customers: db.CustomerModel
    }, {
      purchase_invoices: db.PurchaseInvoiceModel
    }, {
      sales_invoices: db.SalesInvoiceModel
    }
  ];

  _.forEach(resources, function(resource) {
    return _.forIn(resource, function(model, controller) {
      return console.log("exports[" + controller + "] =\n    retrieve: (req, res) ->\n        if req.params.id?\n            db.show\n                res: res\n                " + model + ": " + model + "\n                id: req.params.id\n        else\n            db.index\n                res: res\n                " + model + ": " + model + "\n                populateField: ['suppliers', 'details.item', 'details.item.supplier_id']\n\n    create: (req, res) ->\n        fields = _.keys(req.body)\n        values = _.map fields, (field) -> req.body[field]\n        content = _.zipObject(fields, values)\n\n        db.create\n            res: res\n            " + model + ": " + model + "\n            body: content\n\n    update: (req, res) ->\n        fields = _.keys(req.body)\n        values = _.map fields, (field) -> req.body[field]\n        content = _.zipObject(fields, values)\n\n        db.update\n            res: res\n            " + model + ": " + model + "\n            id: req.params.id\n            replace: (data) -> data = content\n\n    patch: (req, res) ->\n        db.update\n            res: res\n            " + model + ": " + model + "\n            id: req.body.pk\n            replace: (data) -> data[req.body.name] = req.body.value\n\n    delete: (req, res) ->\n        db.destroy\n            res: res\n            " + model + ": " + model + "\n            id: req.params.id");
    });
  });

}).call(this);
